include(common)

find_lib(PicoDsDep_LIBRARIES SHARED LIBS  pico_core avrocpp parquet_abi03 arrow_abi03 re2 double-conversion thrift snappy lz4 boost_filesystem boost_iostreams z )
find_lib(PicoDsDep_STATIC_LIBRARIES STATIC LIBS  pico_core_static avrocpp_s parquet_abi03 arrow_abi03 re2 double-conversion thrift snappy lz4 boost_filesystem boost_iostreams z)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(PicoDsDep DEFAULT_MSG PicoDsDep_LIBRARIES)
find_package_handle_standard_args(PicoDsDep_STATIC DEFAULT_MSG PicoDsDep_STATIC_LIBRARIES)
mark_as_advanced(PicoDsDep_LIBRARIES)
mark_as_advanced(PicoDsDep_STATIC_LIBRARIES)
